default['file']['wordpress'] = 'https://github.com/yhidetoshi/wordpress'
default['path']['wordpress'] = '/var/www/wordpress'
default['mysql']['root_password'] = 'password'
default['mysql']['db_name'] = 'wordpress'
default['mysql']['user']['name']= 'wpadmin'
default['mysql']['user']['password'] = 'password'
default['web']['name'] = 'nginx'
